site_name: "Auto Calib"
site_description: "Short description of the project"
repo_url: "https://github.com/DALSA-Lab/test"
theme: readthedocs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mkdocstrings
  - mermaid2:
      version: '10.1.0'
      arguments:
        theme: 'dark'
        themeVariables:
          primaryColor: '#BB2528'
          primaryTextColor: '#fff'
          primaryBorderColor: '#7C0000'
          lineColor: '#F8B229'
          secondaryColor: '#006100'
          tertiaryColor: '#fff'
nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Component Diagrams:
      - Template: architecture/component_diagrams/component-template.md
  - API:
    - Overview: api/README.md
    - Module: api/module.md
    - CPPPKG: api/cpp_pkg/index.md
    - C++ API Docs: api-cpp/html/index.html
  - Examples:
    - Overview: examples/README.md

extra_javascript:
    - https://unpkg.com/mermaid@8.8.2/dist/mermaid.min.js