
site_name: "Auto Calib"
site_description: "Short description of the project"
repo_url: "https://github.com/DALSA-lab/auto_calib"
theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - System Diagram: architecture/system_diagram.md
    - Component Diagrams:
      - Template: architecture/component_diagrams/component-template.md
  - API:
    - Overview: api/README.md
    - OpenAPI (raw): api/openapi.yaml
  - Examples:
    - Overview: examples/README.md
    - C++: examples/cpp/README.md
