
site_name: "Auto Calib"
site_description: "Short description of the project"
repo_url: "https://github.com/DALSA-Lab/test"
theme:
  name: mkdocs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Component Diagrams:
      - Template: architecture/component_diagrams/component-template.md
  - API:
    - Overview: api/README.md
  - Examples:
    - Overview: examples/README.md
