
site_name: "Auto Calib"
site_description: "Short description of the project"
repo_url: "https://github.com/DALSA-lab/auto_calib"
theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mermaid2
nav:
  - Home: docs/index.md
  - Architecture:
    - Overview: docs/architecture/overview.md
    - System Diagram: docs/architecture/system_diagram.md
    - Component Diagrams:
      - Template: docs/architecture/component_diagrams/component-template.md
  - API:
    - README: docs/api/README.md
    - OpenAPI: docs/api/openapi.yaml
  - Examples:
    - README: docs/examples/README.md
